name: smart_fitness_pod
description: A cross-platform workout tracker with wearable sensor

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.30.0  # 添加这一行
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  csv: ^5.0.3
  fl_chart: ^0.66.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # 如果你还需要权限处理，可以添加：
  # permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - i18n/